name: HelloWorld Workflow
on: workflow_dispatch
jobs: 
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello step
#Running Multiple Shell Commands in single step
        run: |
         echo "This is first line"
         echo "This is second line"
        
