name: HelloWorld Workflow
on: workflow_dispatch
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - run: echo "Building demo app"
      
  test:
   needs: build
   runs-on: ubuntu-latest
   steps:
    - run: echo "Testing demo app"
      
  deploy:
   needs: test
   runs-on: ubuntu-latest
   steps:
     - run: echo "Deploying the demo app"
       
