name: HelloWorld Workflow
on: workflow_dispatch
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - name: Build Phase
      run: echo "Building demo app"
      
  test:
   runs-on: ubuntu-latest
   steps:
    - name: Test Phase
      run: echo "Testing demo app"
      
  deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Deployment Phase
       run: echo "Deploying the demo app"
